//--Generated by Copilot
package stepDef.common;

import cucumber.TestContext;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import stepDef.common.helpers.BrowserHelper;
import stepDef.common.helpers.PageHelper;

/**
 * CommonSteps consolidates shared step definitions across all feature modules
 * to eliminate duplication of browser initialization and navigation logic.
 * Uses Cucumber regex patterns to support multiple Gherkin phrasings.
 */
public class CommonSteps {
    private TestContext testContext;
    private BrowserHelper browserHelper;
    private PageHelper pageHelper;
    
    public CommonSteps(TestContext context) {
        this.testContext = context;
        this.browserHelper = new BrowserHelper(context);
        this.pageHelper = new PageHelper(context);
    }
    
    /**
     * Initializes browser for test execution
     */
    @Given("User launch the browser")
    public void user_launch_the_browser() {
        browserHelper.initializeBrowser();
    }
    
    /**
     * Initializes browser for test execution (alternate phrasing)
     */
    @Given("User launches the browser")
    public void user_launches_the_browser() {
        browserHelper.initializeBrowser();
    }
    
    /**
     * Navigates to URL specified by property key
     * Supports:
     * - "User navigates to URL {string}"
     */
    @Given("User navigates to URL {string}")
    public void user_navigates_to_url(String urlPropertyKey) {
        browserHelper.navigateToUrl(urlPropertyKey);
    }
    
    /**
     * Initializes browser and navigates to site in one step
     * Supports:
     * - "User navigates to the site {string}"
     */
    @Given("User navigates to the site {string}")
    public void user_navigates_to_the_site(String urlPropertyKey) {
        browserHelper.initializeBrowserAndNavigate(urlPropertyKey);
    }
    
    /**
     * Navigates to login page using TestLoginURL property
     */
    @Given("User navigates to the login page")
    public void user_navigates_to_the_login_page() {
        browserHelper.navigateToUrl("TestLoginURL");
    }
    
    /**
     * Navigates to login page using TestLoginURL property (alternate phrasing)
     */
    @Given("User is on the login page")
    public void user_is_on_the_login_page() {
        browserHelper.navigateToUrl("TestLoginURL");
    }
    
    /**
     * Closes browser and cleans up ThreadLocal driver
     * Supports:
     * - "User closes the browser"
     */
    @Then("User closes the browser")
    public void user_closes_the_browser() {
        testContext.closeDriver();
    }
}
