package UnitTestTry;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.ArrayList;
import java.util.List;

/**
 * Shape class representing a polygon with multiple points.
 * --Generated by Copilot
 * Demonstrates PASSING multiple Point objects to another class.
 * 
 * @author Copilot
 * @version 1.0
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class Shape {
    private String name;
    @Builder.Default
    private List<Point3D> vertices = new ArrayList<>();
    
    /**
     * INLINE EDIT 18: Add vertex to shape
     * Demonstrates accepting Point object as parameter
     */
    public void addVertex(Point3D point) {
        vertices.add(point);
    }
    
    /**
     * INLINE EDIT 19: Get perimeter by calculating distances between consecutive points
     * Demonstrates iterating over Point objects and using their methods
     */
    public double getPerimeter() {
        if (vertices.size() < 2) return 0;
        
        double perimeter = 0;
        for (int i = 0; i < vertices.size(); i++) {
            Point3D current = vertices.get(i);
            Point3D next = vertices.get((i + 1) % vertices.size());
            perimeter += current.calculateDistance(next);
        }
        return perimeter;
    }
    
    /**
     * INLINE EDIT 20: Get center point (centroid) of shape
     * Demonstrates creating new Point from multiple Point objects
     */
    public Point3D getCentroid() {
        if (vertices.isEmpty()) return new Point3D(0, 0);
        
        double sumX = 0, sumY = 0;
        for (Point3D point : vertices) {
            sumX += point.getX();
            sumY += point.getY();
        }
        return new Point3D(sumX / vertices.size(), sumY / vertices.size());
    }
    
    /**
     * INLINE EDIT 21: Translate entire shape
     * Demonstrates modifying all Point objects in collection
     */
    public Shape translate(double dx, double dy) {
        for (int i = 0; i < vertices.size(); i++) {
            vertices.set(i, vertices.get(i).translatedCopy(dx, dy));
        }
        return this;
    }
    
    /**
     * INLINE EDIT 22: Check if shape contains a point
     * Demonstrates searching for Point in collection
     */
    public boolean hasVertex(Point3D point) {
        for (Point3D vertex : vertices) {
            if (vertex.isCloseTo(point, 0.001)) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * INLINE EDIT 23: Get bounding box of shape
     * Returns array of Points [bottomLeft, topRight]
     */
    public Point3D[] getBoundingBox() {
        if (vertices.isEmpty()) return new Point3D[]{new Point3D(0, 0), new Point3D(0, 0)};
        
        double minX = vertices.get(0).getX();
        double maxX = minX;
        double minY = vertices.get(0).getY();
        double maxY = minY;
        
        for (Point3D point : vertices) {
            minX = Math.min(minX, point.getX());
            maxX = Math.max(maxX, point.getX());
            minY = Math.min(minY, point.getY());
            maxY = Math.max(maxY, point.getY());
        }
        
        return new Point3D[]{new Point3D(minX, minY), new Point3D(maxX, maxY)};
    }
}
