//--Generated by Copilot
package stepDef.registration;

import cucumber.TestContext;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.testng.Assert;
import pages.Login.RegistrationPage;
import stepDef.common.helpers.PageHelper;

/**
 * RegistrationSteps contains all registration-specific step definitions.
 * Refactored to use PageHelper for cached page access and consolidate duplicate methods.
 * Uses Cucumber regex patterns to handle multiple Gherkin phrasings with single methods.
 */
public class RegistrationSteps {
    private TestContext testContext;
    private PageHelper pageHelper;
    
    public RegistrationSteps(TestContext context) {
        this.testContext = context;
        this.pageHelper = new PageHelper(context);
    }
    
    @Given("User is on the signup section of the login page")
    public void user_is_on_the_signup_section_of_the_login_page() {
        Assert.assertTrue(pageHelper.getRegistrationPage().isOnSignupSection(), 
            "User is not on signup section");
    }
    
    @Given("There is already a registered user with email {string}")
    public void there_is_already_a_registered_user_with_email(String email) {
        // Precondition - documents existing test data requirement
        // In real scenario, this would be a database setup
    }
    
    @When("User enters name {string} in signup form")
    public void user_enters_name_in_signup_form(String name) {
        pageHelper.getRegistrationPage().enterSignupName(name);
    }
    
    @When("User enters email {string} in signup form")
    public void user_enters_email_in_signup_form(String email) {
        pageHelper.getRegistrationPage().enterSignupEmail(email);
    }
    
    @When("User enters unique email {string} in signup form")
    public void user_enters_unique_email_in_signup_form(String email) {
        pageHelper.getRegistrationPage().enterSignupEmail(email);
    }
    
    @When("User enters invalid email {string} in signup form")
    public void user_enters_invalid_email_in_signup_form(String email) {
        pageHelper.getRegistrationPage().enterSignupEmail(email);
    }
    
    @When("User enters password {string} in signup form")
    public void user_enters_password_in_signup_form(String password) {
        pageHelper.getRegistrationPage().enterSignupPassword(password);
    }
    
    @When("User enters valid password {string} in signup form")
    public void user_enters_valid_password_in_signup_form(String password) {
        pageHelper.getRegistrationPage().enterSignupPassword(password);
    }
    
    @When("User enters invalid password {string} that does not meet requirements")
    public void user_enters_invalid_password_that_does_not_meet_requirements(String password) {
        pageHelper.getRegistrationPage().enterSignupPassword(password);
    }
    
    @When("User clicks on {string}")
    public void user_clicks_on(String buttonLocator) {
        pageHelper.getRegistrationPage().clickSignupButton();
    }
    
    @When("User leaves name field empty in signup form")
    public void user_leaves_name_field_empty_in_signup_form() {
        pageHelper.getRegistrationPage().leaveNameFieldEmpty();
    }
    
    @When("User leaves email field empty in signup form")
    public void user_leaves_email_field_empty_in_signup_form() {
        pageHelper.getRegistrationPage().leaveEmailFieldEmpty();
    }
    
    @When("User leaves password field empty in signup form")
    public void user_leaves_password_field_empty_in_signup_form() {
        pageHelper.getRegistrationPage().leavePasswordFieldEmpty();
    }
    
    @Then("User should see success message {string}")
    public void user_should_see_success_message(String expectedMessage) {
        pageHelper.getRegistrationPage().verifySuccessMessage(expectedMessage);
    }
    
    @Then("User should see error message {string}")
    public void user_should_see_error_message(String expectedMessage) {
        pageHelper.getRegistrationPage().verifyErrorMessage(expectedMessage);
    }
    
    @Then("User account should be created in the system")
    public void user_account_should_be_created_in_the_system() {
        Assert.assertTrue(pageHelper.getRegistrationPage().isRegistrationSuccessful(), 
            "User account was not created successfully");
    }
    
    @Then("User should be able to login with email {string} and password {string}")
    public void user_should_be_able_to_login_with_email_and_password(String email, String password) {
        // This step would involve navigating to login and attempting login
        pageHelper.getLoginPage().enterUsernameAndPassword(email, password);
    }
    
    @Then("Verify registration status {string} and verify message {string}")
    public void verify_registration_status_and_verify_message(String isSuccess, String message) {
        pageHelper.getRegistrationPage().verifyRegistrationStatus(isSuccess, message);
    }
    
    @Then("Registration should fail")
    public void registration_should_fail() {
        pageHelper.getRegistrationPage().verifyRegistrationFailed();
    }
    
    @Then("Signup form should retain entered name {string}")
    public void signup_form_should_retain_entered_name(String expectedName) {
        pageHelper.getRegistrationPage().verifyFormRetainsName(expectedName);
    }
    
    @Then("Password field should be empty for security")
    public void password_field_should_be_empty_for_security() {
        pageHelper.getRegistrationPage().verifyPasswordFieldIsEmpty();
    }
    
    @Then("No new account should be created")
    public void no_new_account_should_be_created() {
        Assert.assertFalse(pageHelper.getRegistrationPage().isRegistrationSuccessful(), 
            "No account should have been created");
    }
    
    @Then("Registration should not proceed")
    public void registration_should_not_proceed() {
        pageHelper.getRegistrationPage().verifyRegistrationDidNotProceed();
    }
    
    @Then("No account should be created for email {string}")
    public void no_account_should_be_created_for_email(String email) {
        pageHelper.getRegistrationPage().verifyNoAccountCreated(email);
    }
    
    @Then("User should see validation error {string} for name field")
    public void user_should_see_validation_error_for_name_field(String errorText) {
        pageHelper.getRegistrationPage().verifyFieldValidationError(errorText, "name");
    }
    
    @Then("User should see validation error {string} for email field")
    public void user_should_see_validation_error_for_email_field(String errorText) {
        pageHelper.getRegistrationPage().verifyFieldValidationError(errorText, "email");
    }
    
    @Then("User should see validation error {string} for password field")
    public void user_should_see_validation_error_for_password_field(String errorText) {
        pageHelper.getRegistrationPage().verifyFieldValidationError(errorText, "password");
    }
    
    @Then("Registration form should not submit")
    public void registration_form_should_not_submit() {
        pageHelper.getRegistrationPage().verifyFormDidNotSubmit();
    }
    
    @Then("No account should be created")
    public void no_account_should_be_created() {
        Assert.assertFalse(pageHelper.getRegistrationPage().isRegistrationSuccessful(), 
            "No account should have been created");
    }
}
