//--Generated by Copilot
package pages.Login;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.PageFactory;
import org.testng.Assert;
import utils.ElementUtil;
import utils.ObjectRepository;
import utils.PropertiesFileManager;

public class RegistrationPage {
    WebDriver driver;
    ElementUtil elementutil;
    Logger logger = LogManager.getLogger(RegistrationPage.class);
    
    // Locators - NEVER hardcode, use ObjectRepository
    By signupNameField = ObjectRepository.getLocator("SIGNUP_NAME_FIELD");
    By signupEmailField = ObjectRepository.getLocator("SIGNUP_EMAIL_FIELD");
    By signupPasswordField = ObjectRepository.getLocator("SIGNUP_PASSWORD_FIELD");
    By signupButton = ObjectRepository.getLocator("SIGNUP_BUTTON");
    By successMessage = ObjectRepository.getLocator("SIGNUP_SUCCESS_MESSAGE");
    By errorMessage = ObjectRepository.getLocator("SIGNUP_ERROR_MESSAGE");
    By emailExistError = ObjectRepository.getLocator("EMAIL_EXIST_ERROR");
    By fieldValidationError = ObjectRepository.getLocator("FIELD_VALIDATION_ERROR");
    By loginSection = ObjectRepository.getLocator("LOGIN_SECTION");
    
    // Constructor - MANDATORY pattern
    public RegistrationPage(WebDriver driver) {
        this.driver = driver;
        elementutil = new ElementUtil(driver);
        PageFactory.initElements(driver, this);
    }
    
    // Navigation method
    public void navigateToRegistrationPage(String urlKey) {
        String url = PropertiesFileManager.getPropertyValue(urlKey);
        logger.info("Navigating to registration page: {}", url);
        driver.navigate().to(url);
    }
    
    // Check if user is on signup section
    public boolean isOnSignupSection() {
        logger.info("Verifying user is on signup section");
        return elementutil.isElementDisplayed(signupNameField);
    }
    
    // Action methods - Use ElementUtil wrapper
    public void enterSignupName(String name) {
        logger.info("Entering name in signup form: {}", name);
        elementutil.doSendKeys(signupNameField, name);
    }
    
    public void enterSignupEmail(String email) {
        logger.info("Entering email in signup form: {}", email);
        elementutil.doSendKeys(signupEmailField, email);
    }
    
    public void enterSignupPassword(String password) {
        logger.info("Entering password in signup form");
        elementutil.doSendKeys(signupPasswordField, password);
    }
    
    public void clickSignupButton() {
        logger.info("Clicking signup button");
        elementutil.doClick(signupButton);
    }
    
    public void leaveNameFieldEmpty() {
        logger.info("Leaving name field empty");
        elementutil.doSendKeys(signupNameField, "");
    }
    
    public void leaveEmailFieldEmpty() {
        logger.info("Leaving email field empty");
        elementutil.doSendKeys(signupEmailField, "");
    }
    
    public void leavePasswordFieldEmpty() {
        logger.info("Leaving password field empty");
        elementutil.doSendKeys(signupPasswordField, "");
    }
    
    // Complete registration method
    public void performRegistration(String name, String email, String password) {
        logger.info("Performing registration with name: {}, email: {}", name, email);
        enterSignupName(name);
        enterSignupEmail(email);
        enterSignupPassword(password);
        clickSignupButton();
    }
    
    // Verification methods
    public void verifySuccessMessage(String expectedMessage) {
        logger.info("Verifying success message");
        elementutil.waitForElementToBePresent(successMessage);
        String actualMessage = elementutil.getTextOfElement(successMessage);
        Assert.assertEquals(actualMessage, expectedMessage, "Success message verification failed");
    }
    
    public void verifyErrorMessage(String expectedMessage) {
        logger.info("Verifying error message: {}", expectedMessage);
        String actualMessage = elementutil.getTextOfElement(errorMessage);
        Assert.assertEquals(actualMessage, expectedMessage, "Error message verification failed");
    }
    
    public void verifyEmailExistError(String expectedMessage) {
        logger.info("Verifying email already exists error");
        elementutil.waitForElementToBePresent(emailExistError);
        String actualMessage = elementutil.getTextOfElement(emailExistError);
        Assert.assertEquals(actualMessage, expectedMessage, "Email exist error verification failed");
    }
    
    public void verifyRegistrationStatus(String isSuccess, String expectedMessage) {
        logger.info("Verifying registration status: {}", isSuccess);
        String actualMessage;
        if (isSuccess.equalsIgnoreCase("Y")) {
            elementutil.waitForElementToBePresent(successMessage);
            actualMessage = elementutil.getTextOfElement(successMessage);
        } else {
            // Check for specific error types
            if (elementutil.isElementDisplayed(emailExistError)) {
                actualMessage = elementutil.getTextOfElement(emailExistError);
            } else if (elementutil.isElementDisplayed(errorMessage)) {
                actualMessage = elementutil.getTextOfElement(errorMessage);
            } else {
                actualMessage = elementutil.getTextOfElement(fieldValidationError);
            }
        }
        Assert.assertEquals(actualMessage, expectedMessage, "Registration status verification failed");
    }
    
    public void verifyFieldValidationError(String errorText, String fieldName) {
        logger.info("Verifying validation error for field: {}", fieldName);
        String actualError = elementutil.getTextOfElement(fieldValidationError);
        Assert.assertTrue(actualError.contains(errorText), 
            "Validation error not found for field: " + fieldName);
    }
    
    public boolean isRegistrationSuccessful() {
        return elementutil.isElementDisplayed(successMessage);
    }
    
    public boolean isOnLoginPage() {
        return elementutil.isElementDisplayed(loginSection);
    }
    
    public String getSignupNameFieldValue() {
        return elementutil.getElement(signupNameField).getAttribute("value");
    }
    
    public String getSignupPasswordFieldValue() {
        return elementutil.getElement(signupPasswordField).getAttribute("value");
    }
    
    public void verifyFormRetainsName(String expectedName) {
        logger.info("Verifying signup form retains entered name");
        String actualName = getSignupNameFieldValue();
        Assert.assertEquals(actualName, expectedName, "Form did not retain the entered name");
    }
    
    public void verifyPasswordFieldIsEmpty() {
        logger.info("Verifying password field is empty for security");
        String passwordValue = getSignupPasswordFieldValue();
        Assert.assertTrue(passwordValue.isEmpty(), "Password field should be empty");
    }
    
    // Account verification method (would typically check via API or database)
    public void verifyAccountCreated(String email) {
        logger.info("Verifying account created for email: {}", email);
        // This would typically involve API call or database check
        // For automation, we verify by checking success message
        Assert.assertTrue(isRegistrationSuccessful(), "Account was not created successfully");
    }
    
    public void verifyNoAccountCreated(String email) {
        logger.info("Verifying no account created for email: {}", email);
        Assert.assertFalse(isRegistrationSuccessful(), "Account should not have been created");
    }
    
    public void verifyRegistrationFailed() {
        logger.info("Verifying registration failed");
        Assert.assertFalse(isRegistrationSuccessful(), "Registration should have failed");
    }
    
    public void verifyRegistrationDidNotProceed() {
        logger.info("Verifying registration did not proceed");
        // Verify user is still on the same page
        Assert.assertTrue(isOnLoginPage(), "User should still be on login page");
    }
    
    public void verifyFormDidNotSubmit() {
        logger.info("Verifying form did not submit");
        // Check if validation errors are displayed
        Assert.assertTrue(elementutil.isElementDisplayed(fieldValidationError), 
            "Form should show validation errors");
    }
}
