//--Generated by Copilot
package stepDef.common.helpers;

import cucumber.TestContext;
import driverFactory.DriverManager;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.WebDriver;
import utils.PropertiesFileManager;

/**
 * BrowserHelper provides centralized browser initialization and navigation logic
 * to eliminate code duplication across step definitions.
 * Follows Picocontainer DI pattern with constructor injection of TestContext.
 */
public class BrowserHelper {
    private TestContext testContext;
    private Logger logger = LogManager.getLogger(BrowserHelper.class);
    
    public BrowserHelper(TestContext testContext) {
        this.testContext = testContext;
    }
    
    /**
     * Initializes browser using system property -Dbrowser (defaults to edge)
     * Sets up ThreadLocal WebDriver for parallel execution safety
     */
    public void initializeBrowser() {
        logger.info("Initializing browser for test execution");
        String environmentName = DriverManager.returnEnvironment();
        String browserName = DriverManager.returnBrowserName();
        testContext.initializeDriver(browserName);
        logger.info("Browser initialized: {} in {} environment", browserName, environmentName);
    }
    
    /**
     * Initializes browser and navigates to specified URL property
     * @param urlPropertyKey Property key from environment.properties (e.g., "TestLoginURL")
     */
    public void initializeBrowserAndNavigate(String urlPropertyKey) {
        initializeBrowser();
        navigateToUrl(urlPropertyKey);
    }
    
    /**
     * Navigates to URL resolved from property key
     * @param urlPropertyKey Property key from environment.properties
     */
    public void navigateToUrl(String urlPropertyKey) {
        String url = PropertiesFileManager.getPropertyValue(urlPropertyKey);
        WebDriver driver = testContext.getDriver();
        logger.info("Navigating to URL: {} (property: {})", url, urlPropertyKey);
        driver.navigate().to(url);
    }
    
    /**
     * Gets current environment name (QA/UAT) from system property -Denv
     * @return Environment name (defaults to QA)
     */
    public String getEnvironmentName() {
        return DriverManager.returnEnvironment();
    }
    
    /**
     * Gets current browser name from system property -Dbrowser
     * @return Browser name (defaults to edge)
     */
    public String getBrowserName() {
        return DriverManager.returnBrowserName();
    }
}
