//--Generated by Copilot
package stepDef.common.helpers;

import cucumber.TestContext;
import pages.Login.LoginPage;
import pages.Login.RegistrationPage;

/**
 * PageHelper provides cached access to page objects via PageObjectManager
 * to eliminate repeated page object retrieval calls across step definitions.
 * Follows lazy-initialization singleton pattern per test context.
 */
public class PageHelper {
    private TestContext testContext;
    private LoginPage loginPage;
    private RegistrationPage registrationPage;
    
    public PageHelper(TestContext testContext) {
        this.testContext = testContext;
    }
    
    /**
     * Gets LoginPage instance with caching to avoid repeated PageObjectManager calls
     * @return Cached or newly created LoginPage instance
     */
    public LoginPage getLoginPage() {
        if (loginPage == null) {
            loginPage = testContext.getPageObjectManager().getLoginPage();
        }
        return loginPage;
    }
    
    /**
     * Gets RegistrationPage instance with caching to avoid repeated PageObjectManager calls
     * @return Cached or newly created RegistrationPage instance
     */
    public RegistrationPage getRegistrationPage() {
        if (registrationPage == null) {
            registrationPage = testContext.getPageObjectManager().getRegistrationPage();
        }
        return registrationPage;
    }
    
    /**
     * Clears cached page objects (useful for scenarios requiring fresh page instances)
     */
    public void clearCache() {
        loginPage = null;
        registrationPage = null;
    }
}
