//--Generated by Copilot
package stepDef.common.helpers;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.By;
import org.testng.Assert;
import utils.ElementUtil;

/**
 * VerificationHelper provides standardized assertion patterns
 * to eliminate verification logic duplication across page objects and step definitions.
 * Encapsulates common TestNG assertion patterns with proper logging.
 */
public class VerificationHelper {
    private ElementUtil elementUtil;
    private Logger logger = LogManager.getLogger(VerificationHelper.class);
    
    public VerificationHelper(ElementUtil elementUtil) {
        this.elementUtil = elementUtil;
    }
    
    /**
     * Verifies text content of an element matches expected value
     * @param locator Element locator
     * @param expectedMessage Expected text content
     * @param failureMessage Custom failure message for assertion
     */
    public void verifyElementText(By locator, String expectedMessage, String failureMessage) {
        String actualMessage = elementUtil.getTextOfElement(locator);
        logger.info("Verifying element text - Expected: {}, Actual: {}", expectedMessage, actualMessage);
        Assert.assertEquals(actualMessage, expectedMessage, failureMessage);
    }
    
    /**
     * Verifies message based on success/failure condition with different locators
     * @param isSuccess Whether operation was successful
     * @param successLocator Locator for success message element
     * @param failureLocator Locator for failure message element
     * @param expectedMessage Expected message text
     * @param failureMessage Custom failure message for assertion
     */
    public void verifyConditionalMessage(boolean isSuccess, By successLocator, 
                                          By failureLocator, String expectedMessage, 
                                          String failureMessage) {
        By targetLocator = isSuccess ? successLocator : failureLocator;
        if (isSuccess) {
            elementUtil.waitForElementToBePresent(successLocator);
        }
        String actualMessage = elementUtil.getTextOfElement(targetLocator);
        logger.info("Verifying conditional message - Success: {}, Expected: {}, Actual: {}", 
                    isSuccess, expectedMessage, actualMessage);
        Assert.assertEquals(actualMessage, expectedMessage, failureMessage);
    }
    
    /**
     * Verifies element is displayed on page
     * @param locator Element locator
     * @param elementName Descriptive element name for error message
     */
    public void verifyElementDisplayed(By locator, String elementName) {
        boolean isDisplayed = elementUtil.isElementDisplayed(locator);
        logger.info("Verifying element displayed: {} - Result: {}", elementName, isDisplayed);
        Assert.assertTrue(isDisplayed, elementName + " should be displayed");
    }
    
    /**
     * Verifies element is NOT displayed on page
     * @param locator Element locator
     * @param elementName Descriptive element name for error message
     */
    public void verifyElementNotDisplayed(By locator, String elementName) {
        boolean isDisplayed = elementUtil.isElementDisplayed(locator);
        logger.info("Verifying element NOT displayed: {} - Result: {}", elementName, !isDisplayed);
        Assert.assertFalse(isDisplayed, elementName + " should NOT be displayed");
    }
    
    /**
     * Verifies boolean condition is true
     * @param condition Condition to verify
     * @param failureMessage Custom failure message
     */
    public void verifyTrue(boolean condition, String failureMessage) {
        logger.info("Verifying condition is true: {}", condition);
        Assert.assertTrue(condition, failureMessage);
    }
    
    /**
     * Verifies boolean condition is false
     * @param condition Condition to verify
     * @param failureMessage Custom failure message
     */
    public void verifyFalse(boolean condition, String failureMessage) {
        logger.info("Verifying condition is false: {}", condition);
        Assert.assertFalse(condition, failureMessage);
    }
}
