//--Generated by Copilot
package stepDef.login;

import cucumber.TestContext;
import driverFactory.DriverManager;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import pages.Login.LoginPage;
import stepDef.common.helpers.PageHelper;
import utils.ExcelReader;

import java.io.IOException;
import java.util.List;

import static utils.Constants.TEST_DATA_FILE_PATH;

/**
 * LoginSteps contains all login-specific step definitions.
 * Refactored to use PageHelper for cached page access and eliminate duplication.
 * Browser initialization and navigation steps moved to CommonSteps.
 */
public class LoginSteps {
    private TestContext testContext;
    private PageHelper pageHelper;
    private List<Object[]> testData;
    
    public LoginSteps(TestContext context) {
        this.testContext = context;
        this.pageHelper = new PageHelper(context);
    }
    
    @When("User enters {string} and {string} and click on submit button")
    public void user_enters_and_and_click_on_login(String username, String password) {
        pageHelper.getLoginPage().enterUsernameAndPassword(username, password);
    }
    
    @Then("Verify {string} and verify the {string}")
    public void verify_and_verify_the_message(String isLoginSuccess, String message) {
        pageHelper.getLoginPage().verifyTheMessage(isLoginSuccess, message);
    }
    
    @When("User has test data from Excel")
    public void user_has_test_data_from_excel() throws IOException {
        String excelPath = TEST_DATA_FILE_PATH + DriverManager.returnEnvironment() + "\\TestData\\TestData.xlsx";
        testData = ExcelReader.readExcelDataForLogin(excelPath);
    }
    
    @When("User enters username and password, and clicks on submit button and verify output")
    public void user_enters_username_and_password_and_clicks_on_submit_button() {
        for (Object[] row : testData) {
            String username = (String) row[0];
            String password = (String) row[1];
            String isLoginSuccessful = (String) row[2];
            String message = (String) row[3];
            pageHelper.getLoginPage().enterUsernameAndPassword(username, password);
            pageHelper.getLoginPage().verifyTheMessageFromData(isLoginSuccessful, message);
        }
    }
    
    @Then("Verify login status and message")
    public void verify_login_status_and_message() {
        // Empty method - verification happens in previous step
    }
    
    // Additional login steps for new test scenarios
    
    @When("User enters {string} in the email field")
    public void user_enters_in_the_email_field(String email) {
        pageHelper.getLoginPage().enterUsername(email);
    }
    
    @When("User enters {string} in the password field")
    public void user_enters_in_the_password_field(String password) {
        pageHelper.getLoginPage().enterPassword(password);
    }
    
    @When("User clicks the {string} button")
    public void user_clicks_the_button(String button) {
        pageHelper.getLoginPage().clickLoginButton();
    }
    
    @Then("User should see a personalized message {string}")
    public void user_should_see_a_personalized_message(String message) {
        pageHelper.getLoginPage().verifySuccessMessage(message);
    }
    
    @Then("User should remain on the login page")
    public void user_should_remain_on_the_login_page() {
        pageHelper.getLoginPage().verifyOnLoginPage();
    }
}
