# --Generated by Copilot
# US-002: User Login with Credential Validation
# Epic: LoginModule - User Authentication on AutomationExercise
# URL: https://automationexercise.com/login

@LoginModule @UserAuthentication @QA @UAT
Feature: User Login with Credential Validation
  As a registered user of AutomationExercise
  I want to log in with my email and password
  So that I can access my account and personalized shopping features

  Background:
    Given User launches the browser
    And User navigates to the login page

  # ===============================================
  # HAPPY PATH SCENARIOS - Critical Business Flow
  # ===============================================

  @Smoke @Positive @HighPriority
  Scenario: Successful login with valid credentials
    Given User is on the login page
    When User enters "testuser@example.com" in the email field
    And User enters "Test@123" in the password field
    And User clicks the "Login" button
    Then User should be successfully authenticated
    And User should be redirected to the dashboard
    And User should see a personalized message "Logged in as testuser"
    And A secure session should be created

  # ===============================================
  # NEGATIVE TEST SCENARIOS - Authentication Failures
  # ===============================================

  @Regression @Negative @HighPriority
  Scenario: Login with incorrect password
    Given User is on the login page
    When User enters "testuser@example.com" in the email field
    And User enters "WrongPassword123" in the password field
    And User clicks the "Login" button
    Then The login should fail
    And User should see an error message "Your email or password is incorrect!"
    And User should remain on the login page
    And The password field should be cleared
    And No session should be created

  @Regression @Negative @HighPriority
  Scenario: Login with non-existent email
    Given User is on the login page
    When User enters "nonexistent@example.com" in the email field
    And User enters "Password123" in the password field
    And User clicks the "Login" button
    Then The login should fail
    And User should see an error message "Your email or password is incorrect!"
    And User should remain on the login page
    And No session should be created

  # ===============================================
  # VALIDATION SCENARIOS - Field Validations
  # ===============================================

  @Regression @Negative @Validation
  Scenario: Login with empty email field
    Given User is on the login page
    When User leaves the email field empty
    And User enters "Test@123" in the password field
    And User clicks the "Login" button
    Then User should see validation error "This field is required" for email field
    And The login form should not submit

  @Regression @Negative @Validation
  Scenario: Login with empty password field
    Given User is on the login page
    When User enters "testuser@example.com" in the email field
    And User leaves the password field empty
    And User clicks the "Login" button
    Then User should see validation error "This field is required" for password field
    And The login form should not submit

  @Regression @Negative @Validation
  Scenario: Login with both fields empty
    Given User is on the login page
    When User leaves the email field empty
    And User leaves the password field empty
    And User clicks the "Login" button
    Then User should see validation errors on both fields
    And User should see message "This field is required"
    And The login form should not submit

  # ===============================================
  # EDGE CASE SCENARIOS - Email Format Validation
  # ===============================================

  @EdgeCase @Negative
  Scenario: Login with invalid email format - no @ symbol
    Given User is on the login page
    When User enters "notanemail" in the email field
    And User enters "Test@123" in the password field
    And User clicks the "Login" button
    Then User should see an error message "Please enter a valid email address"
    And The form should not submit

  @EdgeCase @Negative
  Scenario: Login with invalid email format - incomplete domain
    Given User is on the login page
    When User enters "test@" in the email field
    And User enters "Test@123" in the password field
    And User clicks the "Login" button
    Then User should see an error message "Please enter a valid email address"
    And The form should not submit

  @EdgeCase @Negative
  Scenario: Login with invalid email format - missing username
    Given User is on the login page
    When User enters "@example.com" in the email field
    And User enters "Test@123" in the password field
    And User clicks the "Login" button
    Then User should see an error message "Please enter a valid email address"
    And The form should not submit

  # ===============================================
  # SESSION MANAGEMENT SCENARIOS
  # ===============================================

  @Regression @Positive @Integration
  Scenario: Session persistence after login
    Given User has successfully logged in
    When User navigates to other pages within the site
    Then User should remain logged in across all pages
    And User should see "Logged in as testuser" on every page

  @Regression @Positive @Integration
  Scenario: Session persistence with Remember Me selected
    Given User is on the login page
    When User enters "testuser@example.com" in the email field
    And User enters "Test@123" in the password field
    And User selects "Remember Me" checkbox
    And User clicks the "Login" button
    Then User should be successfully authenticated
    When User closes the browser and reopens the site
    Then User should remain logged in

  @Regression @Positive @Integration
  Scenario: Session expiry without Remember Me
    Given User is on the login page
    When User enters "testuser@example.com" in the email field
    And User enters "Test@123" in the password field
    And User does not select "Remember Me" checkbox
    And User clicks the "Login" button
    Then User should be successfully authenticated
    When User closes the browser and reopens the site
    Then User should be logged out

  # ===============================================
  # SECURITY SCENARIOS - Rate Limiting & Brute Force
  # ===============================================

  @Security @Negative
  Scenario: Account lockout after multiple failed attempts
    Given User is on the login page
    When User enters "testuser@example.com" in the email field
    And User enters incorrect password 5 times consecutively
    Then User account should be temporarily locked
    And User should see message "Account locked due to multiple failed attempts. Try again in 15 minutes"
    And User should not be able to login for 15 minutes

  @Security @Positive
  Scenario: Case-insensitive email matching
    Given User is registered with email "TestUser@example.com"
    When User enters "testuser@example.com" in lowercase
    And User enters correct password "Test@123"
    And User clicks the "Login" button
    Then User should be successfully authenticated
    And User should be redirected to the dashboard

  @Security @Negative
  Scenario: Case-sensitive password validation
    Given User is on the login page
    When User enters "testuser@example.com" in the email field
    And User enters "test@123" with incorrect case
    And User clicks the "Login" button
    Then The login should fail
    And User should see an error message "Your email or password is incorrect!"

  # ===============================================
  # DATA-DRIVEN SCENARIOS - Multiple Credential Combinations
  # ===============================================

  @DataDriven @Regression
  Scenario Outline: Login with various credential combinations
    Given User is on the login page
    When User enters "<email>" in the email field
    And User enters "<password>" in the password field
    And User clicks the "Login" button
    Then User should see result "<expectedResult>"
    And User should see message "<expectedMessage>"

    Examples:
      | email                     | password          | expectedResult | expectedMessage                          |
      | testuser@example.com      | Test@123          | Success        | Logged in as testuser                    |
      | testuser@example.com      | WrongPass         | Failure        | Your email or password is incorrect!     |
      | nonexistent@example.com   | Test@123          | Failure        | Your email or password is incorrect!     |
      | invalid-email             | Test@123          | ValidationFail | Please enter a valid email address       |
      |                           | Test@123          | ValidationFail | This field is required                   |
      | testuser@example.com      |                   | ValidationFail | This field is required                   |

  # ===============================================
  # USABILITY SCENARIOS - Keyboard & Accessibility
  # ===============================================

  @Regression @Usability
  Scenario: Login form submission with Enter key
    Given User is on the login page
    When User enters "testuser@example.com" in the email field
    And User enters "Test@123" in the password field
    And User presses Enter key
    Then The login form should submit
    And User should be successfully authenticated

  @Regression @Usability @Accessibility
  Scenario: Tab navigation between form fields
    Given User is on the login page
    When User focuses on email field
    And User presses Tab key
    Then Focus should move to password field
    When User presses Tab key again
    Then Focus should move to Login button

  # ===============================================
  # BUSINESS RULES VALIDATION
  # ===============================================

  @Regression @Negative
  Scenario: Login attempt with deleted account
    Given User account "deleteduser@example.com" has been deleted
    When User attempts to login with deleted account credentials
    Then The login should fail
    And User should see an error message "Your email or password is incorrect!"
    And No session should be created
